"""Bootstrap seed data for the :class:`SearchIndex`.

Populates the in-memory typeahead index with a curated set of popular
instruments across equities, ETFs, crypto, and forex.  This is a
*bootstrap* path — the production index will eventually be backed by
Postgres ``pg_trgm``; this seed ensures the dropdown works from day one.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from engine.reference.model import RefInstrument

if TYPE_CHECKING:
    from engine.reference.search import SearchIndex


def seed_index(index: SearchIndex) -> int:
    for row in _INSTRUMENTS:
        index.add(RefInstrument(**row))
    return len(_INSTRUMENTS)


_INSTRUMENTS: list[dict] = [
    {"primary_ticker": "AAPL", "primary_venue": "XNAS", "asset_class": "equity", "name": "Apple Inc."},
    {"primary_ticker": "MSFT", "primary_venue": "XNAS", "asset_class": "equity", "name": "Microsoft Corp."},
    {"primary_ticker": "GOOGL", "primary_venue": "XNAS", "asset_class": "equity", "name": "Alphabet Inc."},
    {"primary_ticker": "GOOG", "primary_venue": "XNAS", "asset_class": "equity", "name": "Alphabet Inc. Class C"},
    {"primary_ticker": "AMZN", "primary_venue": "XNAS", "asset_class": "equity", "name": "Amazon.com Inc."},
    {"primary_ticker": "NVDA", "primary_venue": "XNAS", "asset_class": "equity", "name": "NVIDIA Corp."},
    {"primary_ticker": "META", "primary_venue": "XNAS", "asset_class": "equity", "name": "Meta Platforms Inc."},
    {"primary_ticker": "TSLA", "primary_venue": "XNAS", "asset_class": "equity", "name": "Tesla Inc."},
    {"primary_ticker": "BRK.B", "primary_venue": "XNYS", "asset_class": "equity", "name": "Berkshire Hathaway Inc. Class B"},
    {"primary_ticker": "BRK.A", "primary_venue": "XNYS", "asset_class": "equity", "name": "Berkshire Hathaway Inc. Class A"},
    {"primary_ticker": "JPM", "primary_venue": "XNYS", "asset_class": "equity", "name": "JPMorgan Chase & Co."},
    {"primary_ticker": "V", "primary_venue": "XNYS", "asset_class": "equity", "name": "Visa Inc."},
    {"primary_ticker": "JNJ", "primary_venue": "XNYS", "asset_class": "equity", "name": "Johnson & Johnson"},
    {"primary_ticker": "WMT", "primary_venue": "XNYS", "asset_class": "equity", "name": "Walmart Inc."},
    {"primary_ticker": "PG", "primary_venue": "XNYS", "asset_class": "equity", "name": "Procter & Gamble Co."},
    {"primary_ticker": "MA", "primary_venue": "XNYS", "asset_class": "equity", "name": "Mastercard Inc."},
    {"primary_ticker": "HD", "primary_venue": "XNYS", "asset_class": "equity", "name": "Home Depot Inc."},
    {"primary_ticker": "UNH", "primary_venue": "XNYS", "asset_class": "equity", "name": "UnitedHealth Group Inc."},
    {"primary_ticker": "DIS", "primary_venue": "XNYS", "asset_class": "equity", "name": "Walt Disney Co."},
    {"primary_ticker": "BAC", "primary_venue": "XNYS", "asset_class": "equity", "name": "Bank of America Corp."},
    {"primary_ticker": "XOM", "primary_venue": "XNYS", "asset_class": "equity", "name": "Exxon Mobil Corp."},
    {"primary_ticker": "PFE", "primary_venue": "XNYS", "asset_class": "equity", "name": "Pfizer Inc."},
    {"primary_ticker": "KO", "primary_venue": "XNYS", "asset_class": "equity", "name": "Coca-Cola Co."},
    {"primary_ticker": "PEP", "primary_venue": "XNYS", "asset_class": "equity", "name": "PepsiCo Inc."},
    {"primary_ticker": "CSCO", "primary_venue": "XNAS", "asset_class": "equity", "name": "Cisco Systems Inc."},
    {"primary_ticker": "ADBE", "primary_venue": "XNAS", "asset_class": "equity", "name": "Adobe Inc."},
    {"primary_ticker": "CRM", "primary_venue": "XNYS", "asset_class": "equity", "name": "Salesforce Inc."},
    {"primary_ticker": "NFLX", "primary_venue": "XNAS", "asset_class": "equity", "name": "Netflix Inc."},
    {"primary_ticker": "AMD", "primary_venue": "XNAS", "asset_class": "equity", "name": "Advanced Micro Devices Inc."},
    {"primary_ticker": "INTC", "primary_venue": "XNAS", "asset_class": "equity", "name": "Intel Corp."},
    {"primary_ticker": "CMCSA", "primary_venue": "XNAS", "asset_class": "equity", "name": "Comcast Corp."},
    {"primary_ticker": "NKE", "primary_venue": "XNYS", "asset_class": "equity", "name": "Nike Inc."},
    {"primary_ticker": "ABT", "primary_venue": "XNYS", "asset_class": "equity", "name": "Abbott Laboratories"},
    {"primary_ticker": "MRK", "primary_venue": "XNYS", "asset_class": "equity", "name": "Merck & Co. Inc."},
    {"primary_ticker": "T", "primary_venue": "XNYS", "asset_class": "equity", "name": "AT&T Inc."},
    {"primary_ticker": "ORCL", "primary_venue": "XNYS", "asset_class": "equity", "name": "Oracle Corp."},
    {"primary_ticker": "COST", "primary_venue": "XNAS", "asset_class": "equity", "name": "Costco Wholesale Corp."},
    {"primary_ticker": "LLY", "primary_venue": "XNYS", "asset_class": "equity", "name": "Eli Lilly and Co."},
    {"primary_ticker": "AVGO", "primary_venue": "XNAS", "asset_class": "equity", "name": "Broadcom Inc."},
    {"primary_ticker": "TXN", "primary_venue": "XNAS", "asset_class": "equity", "name": "Texas Instruments Inc."},
    {"primary_ticker": "QCOM", "primary_venue": "XNAS", "asset_class": "equity", "name": "Qualcomm Inc."},
    {"primary_ticker": "SBUX", "primary_venue": "XNAS", "asset_class": "equity", "name": "Starbucks Corp."},
    {"primary_ticker": "UBER", "primary_venue": "XNYS", "asset_class": "equity", "name": "Uber Technologies Inc."},
    {"primary_ticker": "SPOT", "primary_venue": "XNYS", "asset_class": "equity", "name": "Spotify Technology S.A."},
    {"primary_ticker": "SQ", "primary_venue": "XNYS", "asset_class": "equity", "name": "Block Inc."},
    {"primary_ticker": "SHOP", "primary_venue": "XNYS", "asset_class": "equity", "name": "Shopify Inc."},
    {"primary_ticker": "SNAP", "primary_venue": "XNYS", "asset_class": "equity", "name": "Snap Inc."},
    {"primary_ticker": "PYPL", "primary_venue": "XNAS", "asset_class": "equity", "name": "PayPal Holdings Inc."},
    {"primary_ticker": "COIN", "primary_venue": "XNAS", "asset_class": "equity", "name": "Coinbase Global Inc."},
    {"primary_ticker": "PLTR", "primary_venue": "XNYS", "asset_class": "equity", "name": "Palantir Technologies Inc."},
    {"primary_ticker": "RIVN", "primary_venue": "XNAS", "asset_class": "equity", "name": "Rivian Automotive Inc."},
    {"primary_ticker": "SOFI", "primary_venue": "XNAS", "asset_class": "equity", "name": "SoFi Technologies Inc."},
    {"primary_ticker": "MCD", "primary_venue": "XNYS", "asset_class": "equity", "name": "McDonald's Corp."},
    {"primary_ticker": "BA", "primary_venue": "XNYS", "asset_class": "equity", "name": "Boeing Co."},
    {"primary_ticker": "CAT", "primary_venue": "XNYS", "asset_class": "equity", "name": "Caterpillar Inc."},
    {"primary_ticker": "GE", "primary_venue": "XNYS", "asset_class": "equity", "name": "GE Aerospace"},
    {"primary_ticker": "IBM", "primary_venue": "XNYS", "asset_class": "equity", "name": "International Business Machines Corp."},
    {"primary_ticker": "GS", "primary_venue": "XNYS", "asset_class": "equity", "name": "Goldman Sachs Group Inc."},
    {"primary_ticker": "MS", "primary_venue": "XNYS", "asset_class": "equity", "name": "Morgan Stanley"},
    {"primary_ticker": "BLK", "primary_venue": "XNYS", "asset_class": "equity", "name": "BlackRock Inc."},
    {"primary_ticker": "SCHW", "primary_venue": "XNYS", "asset_class": "equity", "name": "Charles Schwab Corp."},
    {"primary_ticker": "AXP", "primary_venue": "XNYS", "asset_class": "equity", "name": "American Express Co."},
    {"primary_ticker": "C", "primary_venue": "XNYS", "asset_class": "equity", "name": "Citigroup Inc."},
    {"primary_ticker": "WFC", "primary_venue": "XNYS", "asset_class": "equity", "name": "Wells Fargo & Co."},
    {"primary_ticker": "DELL", "primary_venue": "XNYS", "asset_class": "equity", "name": "Dell Technologies Inc."},
    {"primary_ticker": "EA", "primary_venue": "XNAS", "asset_class": "equity", "name": "Electronic Arts Inc."},
    {"primary_ticker": "ARM", "primary_venue": "XNAS", "asset_class": "equity", "name": "ARM Holdings PLC"},
    {"primary_ticker": "PANW", "primary_venue": "XNYS", "asset_class": "equity", "name": "Palo Alto Networks Inc."},
    {"primary_ticker": "CRWD", "primary_venue": "XNAS", "asset_class": "equity", "name": "CrowdStrike Holdings Inc."},
    {"primary_ticker": "ZS", "primary_venue": "XNYS", "asset_class": "equity", "name": "Zscaler Inc."},
    {"primary_ticker": "DDOG", "primary_venue": "XNAS", "asset_class": "equity", "name": "Datadog Inc."},
    {"primary_ticker": "MDB", "primary_venue": "XNAS", "asset_class": "equity", "name": "MongoDB Inc."},
    {"primary_ticker": "NET", "primary_venue": "XNYS", "asset_class": "equity", "name": "Cloudflare Inc."},
    {"primary_ticker": "SNOW", "primary_venue": "XNYS", "asset_class": "equity", "name": "Snowflake Inc."},
    {"primary_ticker": "SMCI", "primary_venue": "XNAS", "asset_class": "equity", "name": "Super Micro Computer Inc."},
    {"primary_ticker": "VRT", "primary_venue": "XNYS", "asset_class": "equity", "name": "Vertiv Holdings Co."},
    {"primary_ticker": "ANET", "primary_venue": "XNAS", "asset_class": "equity", "name": "Arista Networks Inc."},
    {"primary_ticker": "MRVL", "primary_venue": "XNAS", "asset_class": "equity", "name": "Marvell Technology Inc."},
    {"primary_ticker": "MCHP", "primary_venue": "XNAS", "asset_class": "equity", "name": "Microchip Technology Inc."},
    {"primary_ticker": "SWKS", "primary_venue": "XNAS", "asset_class": "equity", "name": "Skyworks Solutions Inc."},
    {"primary_ticker": "ON", "primary_venue": "XNAS", "asset_class": "equity", "name": "ON Semiconductor Corp."},
    {"primary_ticker": "MU", "primary_venue": "XNAS", "asset_class": "equity", "name": "Micron Technology Inc."},
    {"primary_ticker": "KLAC", "primary_venue": "XNAS", "asset_class": "equity", "name": "KLA Corp."},
    {"primary_ticker": "LRCX", "primary_venue": "XNAS", "asset_class": "equity", "name": "Lam Research Corp."},
    {"primary_ticker": "AMAT", "primary_venue": "XNAS", "asset_class": "equity", "name": "Applied Materials Inc."},
    {"primary_ticker": "ISRG", "primary_venue": "XNAS", "asset_class": "equity", "name": "Intuitive Surgical Inc."},
    {"primary_ticker": "ABNB", "primary_venue": "XNAS", "asset_class": "equity", "name": "Airbnb Inc."},
    {"primary_ticker": "BKNG", "primary_venue": "XNAS", "asset_class": "equity", "name": "Booking Holdings Inc."},
    {"primary_ticker": "LOW", "primary_venue": "XNYS", "asset_class": "equity", "name": "Lowe's Cos. Inc."},
    {"primary_ticker": "TGT", "primary_venue": "XNYS", "asset_class": "equity", "name": "Target Corp."},
    {"primary_ticker": "BBY", "primary_venue": "XNYS", "asset_class": "equity", "name": "Best Buy Co. Inc."},
    {"primary_ticker": "TJX", "primary_venue": "XNYS", "asset_class": "equity", "name": "TJX Cos. Inc."},
    {"primary_ticker": "CVX", "primary_venue": "XNYS", "asset_class": "equity", "name": "Chevron Corp."},
    {"primary_ticker": "COP", "primary_venue": "XNYS", "asset_class": "equity", "name": "ConocoPhillips"},
    {"primary_ticker": "F", "primary_venue": "XNYS", "asset_class": "equity", "name": "Ford Motor Co."},
    {"primary_ticker": "GM", "primary_venue": "XNYS", "asset_class": "equity", "name": "General Motors Co."},
    {"primary_ticker": "TM", "primary_venue": "XNYS", "asset_class": "equity", "name": "Toyota Motor Corp."},
    {"primary_ticker": "BABA", "primary_venue": "XNYS", "asset_class": "equity", "name": "Alibaba Group Holding Ltd."},
    {"primary_ticker": "JD", "primary_venue": "XNAS", "asset_class": "equity", "name": "JD.com Inc."},
    {"primary_ticker": "TCEHY", "primary_venue": "XOTC", "asset_class": "equity", "name": "Tencent Holdings Ltd."},
    {"primary_ticker": "ASML", "primary_venue": "XNAS", "asset_class": "equity", "name": "ASML Holding N.V."},
    {"primary_ticker": "TSM", "primary_venue": "XNYS", "asset_class": "equity", "name": "Taiwan Semiconductor Manufacturing Co."},
    {"primary_ticker": "SAP", "primary_venue": "XNYS", "asset_class": "equity", "name": "SAP SE"},
    {"primary_ticker": "ACN", "primary_venue": "XNYS", "asset_class": "equity", "name": "Accenture PLC"},
    {"primary_ticker": "ABBV", "primary_venue": "XNYS", "asset_class": "equity", "name": "AbbVie Inc."},
    {"primary_ticker": "TMO", "primary_venue": "XNYS", "asset_class": "equity", "name": "Thermo Fisher Scientific Inc."},
    {"primary_ticker": "GEHC", "primary_venue": "XNAS", "asset_class": "equity", "name": "GE HealthCare Technologies Inc."},
    {"primary_ticker": "GEV", "primary_venue": "XNYS", "asset_class": "equity", "name": "GE Vernova Inc."},
    {"primary_ticker": "KVUE", "primary_venue": "XNYS", "asset_class": "equity", "name": "Kenvue Inc."},
    {"primary_ticker": "MDLZ", "primary_venue": "XNAS", "asset_class": "equity", "name": "Mondelez International Inc."},
    {"primary_ticker": "HSY", "primary_venue": "XNYS", "asset_class": "equity", "name": "Hershey Co."},
    {"primary_ticker": "CL", "primary_venue": "XNYS", "asset_class": "equity", "name": "Colgate-Palmolive Co."},
    {"primary_ticker": "EL", "primary_venue": "XNYS", "asset_class": "equity", "name": "Estee Lauder Companies Inc."},
    {"primary_ticker": "KDP", "primary_venue": "XNYS", "asset_class": "equity", "name": "Keurig Dr Pepper Inc."},
    {"primary_ticker": "SHW", "primary_venue": "XNYS", "asset_class": "equity", "name": "Sherwin-Williams Co."},
    {"primary_ticker": "MPC", "primary_venue": "XNYS", "asset_class": "equity", "name": "Marathon Petroleum Corp."},
    {"primary_ticker": "VLO", "primary_venue": "XNYS", "asset_class": "equity", "name": "Valero Energy Corp."},
    {"primary_ticker": "CCI", "primary_venue": "XNYS", "asset_class": "equity", "name": "Crown Castle International Corp."},
    {"primary_ticker": "AMT", "primary_venue": "XNYS", "asset_class": "equity", "name": "American Tower Corp."},
    {"primary_ticker": "O", "primary_venue": "XNYS", "asset_class": "equity", "name": "Realty Income Corp."},
    {"primary_ticker": "VICI", "primary_venue": "XNYS", "asset_class": "equity", "name": "VICI Properties Inc."},
    {"primary_ticker": "PLD", "primary_venue": "XNYS", "asset_class": "equity", "name": "Prologis Inc."},
    {"primary_ticker": "EQIX", "primary_venue": "XNAS", "asset_class": "equity", "name": "Equinix Inc."},
    {"primary_ticker": "DLR", "primary_venue": "XNYS", "asset_class": "equity", "name": "Digital Realty Trust Inc."},
    {"primary_ticker": "SPGI", "primary_venue": "XNYS", "asset_class": "equity", "name": "S&P Global Inc."},
    {"primary_ticker": "ICE", "primary_venue": "XNYS", "asset_class": "equity", "name": "Intercontinental Exchange Inc."},
    {"primary_ticker": "CME", "primary_venue": "XNAS", "asset_class": "equity", "name": "CME Group Inc."},
    {"primary_ticker": "CB", "primary_venue": "XNYS", "asset_class": "equity", "name": "Chubb Ltd."},
    {"primary_ticker": "APO", "primary_venue": "XNYS", "asset_class": "equity", "name": "Apollo Global Management Inc."},
    {"primary_ticker": "BX", "primary_venue": "XNYS", "asset_class": "equity", "name": "Blackstone Inc."},
    {"primary_ticker": "KKR", "primary_venue": "XNYS", "asset_class": "equity", "name": "KKR & Co. Inc."},
    {"primary_ticker": "CG", "primary_venue": "XNYS", "asset_class": "equity", "name": "Carlyle Group Inc."},
    {"primary_ticker": "ARES", "primary_venue": "XNYS", "asset_class": "equity", "name": "Ares Management Corp."},
    {"primary_ticker": "CI", "primary_venue": "XNYS", "asset_class": "equity", "name": "Cigna Group"},
    {"primary_ticker": "CVS", "primary_venue": "XNYS", "asset_class": "equity", "name": "CVS Health Corp."},
    {"primary_ticker": "HUM", "primary_venue": "XNYS", "asset_class": "equity", "name": "Humana Inc."},
    {"primary_ticker": "ELV", "primary_venue": "XNYS", "asset_class": "equity", "name": "Elevance Health Inc."},
    {"primary_ticker": "COR", "primary_venue": "XNYS", "asset_class": "equity", "name": "Cencora Inc."},
    {"primary_ticker": "MCK", "primary_venue": "XNYS", "asset_class": "equity", "name": "McKesson Corp."},
    {"primary_ticker": "CAH", "primary_venue": "XNYS", "asset_class": "equity", "name": "Cardinal Health Inc."},
    {"primary_ticker": "FIS", "primary_venue": "XNYS", "asset_class": "equity", "name": "Fidelity National Information Services Inc."},
    {"primary_ticker": "FISV", "primary_venue": "XNAS", "asset_class": "equity", "name": "Fiserv Inc."},
    {"primary_ticker": "GPN", "primary_venue": "XNYS", "asset_class": "equity", "name": "Global Payments Inc."},
    {"primary_ticker": "MKTX", "primary_venue": "XNAS", "asset_class": "equity", "name": "MarketAxess Holdings Inc."},
    {"primary_ticker": "PNC", "primary_venue": "XNYS", "asset_class": "equity", "name": "PNC Financial Services Group Inc."},
    {"primary_ticker": "USB", "primary_venue": "XNYS", "asset_class": "equity", "name": "U.S. Bancorp"},
    {"primary_ticker": "COF", "primary_venue": "XNYS", "asset_class": "equity", "name": "Capital One Financial Corp."},
    {"primary_ticker": "DFS", "primary_venue": "XNYS", "asset_class": "equity", "name": "Discover Financial Services"},
    {"primary_ticker": "TFC", "primary_venue": "XNYS", "asset_class": "equity", "name": "Truist Financial Corp."},
    {"primary_ticker": "MELI", "primary_venue": "XNAS", "asset_class": "equity", "name": "MercadoLibre Inc."},
    {"primary_ticker": "NU", "primary_venue": "XNYS", "asset_class": "equity", "name": "Nu Holdings Ltd."},
    {"primary_ticker": "SE", "primary_venue": "XNYS", "asset_class": "equity", "name": "Sea Ltd."},
    {"primary_ticker": "GRAB", "primary_venue": "XNAS", "asset_class": "equity", "name": "Grab Holdings Ltd."},
    {"primary_ticker": "PATH", "primary_venue": "XNYS", "asset_class": "equity", "name": "UiPath Inc."},
    {"primary_ticker": "GTLB", "primary_venue": "XNAS", "asset_class": "equity", "name": "GitLab Inc."},
    {"primary_ticker": "OKTA", "primary_venue": "XNAS", "asset_class": "equity", "name": "Okta Inc."},
    {"primary_ticker": "TEAM", "primary_venue": "XNAS", "asset_class": "equity", "name": "Atlassian Corp."},
    {"primary_ticker": "PINS", "primary_venue": "XNYS", "asset_class": "equity", "name": "Pinterest Inc."},
    {"primary_ticker": "ETSY", "primary_venue": "XNAS", "asset_class": "equity", "name": "Etsy Inc."},
    {"primary_ticker": "DKNG", "primary_venue": "XNAS", "asset_class": "equity", "name": "DraftKings Inc."},
    {"primary_ticker": "NIO", "primary_venue": "XNYS", "asset_class": "equity", "name": "NIO Inc."},
    {"primary_ticker": "XPEV", "primary_venue": "XNYS", "asset_class": "equity", "name": "XPeng Inc."},
    {"primary_ticker": "LI", "primary_venue": "XNAS", "asset_class": "equity", "name": "Li Auto Inc."},
    {"primary_ticker": "SOUN", "primary_venue": "XNAS", "asset_class": "equity", "name": "SoundHound AI Inc."},
    {"primary_ticker": "IONQ", "primary_venue": "XNYS", "asset_class": "equity", "name": "IonQ Inc."},
    {"primary_ticker": "RGTI", "primary_venue": "XNAS", "asset_class": "equity", "name": "Rigetti Computing Inc."},
    {"primary_ticker": "QBTS", "primary_venue": "XNYS", "asset_class": "equity", "name": "D-Wave Quantum Inc."},
    {"primary_ticker": "ENPH", "primary_venue": "XNAS", "asset_class": "equity", "name": "Enphase Energy Inc."},
    {"primary_ticker": "FSLR", "primary_venue": "XNAS", "asset_class": "equity", "name": "First Solar Inc."},
    {"primary_ticker": "NEE", "primary_venue": "XNYS", "asset_class": "equity", "name": "NextEra Energy Inc."},
    {"primary_ticker": "FCX", "primary_venue": "XNYS", "asset_class": "equity", "name": "Freeport-McMoRan Inc."},
    {"primary_ticker": "NEM", "primary_venue": "XNYS", "asset_class": "equity", "name": "Newmont Corp."},
    {"primary_ticker": "GOLD", "primary_venue": "XNYS", "asset_class": "equity", "name": "Barrick Gold Corp."},
    {"primary_ticker": "CCJ", "primary_venue": "XNYS", "asset_class": "equity", "name": "Cameco Corp."},
    {"primary_ticker": "DAL", "primary_venue": "XNYS", "asset_class": "equity", "name": "Delta Air Lines Inc."},
    {"primary_ticker": "UAL", "primary_venue": "XNAS", "asset_class": "equity", "name": "United Airlines Holdings Inc."},
    {"primary_ticker": "AAL", "primary_venue": "XNAS", "asset_class": "equity", "name": "American Airlines Group Inc."},
    {"primary_ticker": "LUV", "primary_venue": "XNYS", "asset_class": "equity", "name": "Southwest Airlines Co."},
    {"primary_ticker": "MAR", "primary_venue": "XNYS", "asset_class": "equity", "name": "Marriott International Inc."},
    {"primary_ticker": "HLT", "primary_venue": "XNYS", "asset_class": "equity", "name": "Hilton Worldwide Holdings Inc."},
    {"primary_ticker": "RCL", "primary_venue": "XNYS", "asset_class": "equity", "name": "Royal Caribbean Cruises Ltd."},
    {"primary_ticker": "CCL", "primary_venue": "XNYS", "asset_class": "equity", "name": "Carnival Corp."},
    {"primary_ticker": "EXPE", "primary_venue": "XNAS", "asset_class": "equity", "name": "Expedia Group Inc."},
    {"primary_ticker": "ONON", "primary_venue": "XNYS", "asset_class": "equity", "name": "On Holding AG"},
    {"primary_ticker": "DECK", "primary_venue": "XNYS", "asset_class": "equity", "name": "Deckers Outdoor Corp."},
    {"primary_ticker": "SPY", "primary_venue": "XASE", "asset_class": "etf", "name": "SPDR S&P 500 ETF Trust"},
    {"primary_ticker": "VOO", "primary_venue": "XASE", "asset_class": "etf", "name": "Vanguard S&P 500 ETF"},
    {"primary_ticker": "IVV", "primary_venue": "XASE", "asset_class": "etf", "name": "iShares Core S&P 500 ETF"},
    {"primary_ticker": "QQQ", "primary_venue": "XNAS", "asset_class": "etf", "name": "Invesco QQQ Trust"},
    {"primary_ticker": "IWM", "primary_venue": "XASE", "asset_class": "etf", "name": "iShares Russell 2000 ETF"},
    {"primary_ticker": "DIA", "primary_venue": "XASE", "asset_class": "etf", "name": "SPDR Dow Jones Industrial Average ETF"},
    {"primary_ticker": "VTI", "primary_venue": "XASE", "asset_class": "etf", "name": "Vanguard Total Stock Market ETF"},
    {"primary_ticker": "VEA", "primary_venue": "XASE", "asset_class": "etf", "name": "Vanguard FTSE Developed Markets ETF"},
    {"primary_ticker": "EEM", "primary_venue": "XASE", "asset_class": "etf", "name": "iShares MSCI Emerging Markets ETF"},
    {"primary_ticker": "VWO", "primary_venue": "XASE", "asset_class": "etf", "name": "Vanguard FTSE Emerging Markets ETF"},
    {"primary_ticker": "AGG", "primary_venue": "XASE", "asset_class": "etf", "name": "iShares Core U.S. Aggregate Bond ETF"},
    {"primary_ticker": "BND", "primary_venue": "XASE", "asset_class": "etf", "name": "Vanguard Total Bond Market ETF"},
    {"primary_ticker": "TLT", "primary_venue": "XASE", "asset_class": "etf", "name": "iShares 20+ Year Treasury Bond ETF"},
    {"primary_ticker": "LQD", "primary_venue": "XASE", "asset_class": "etf", "name": "iShares iBoxx Investment Grade Corporate Bond ETF"},
    {"primary_ticker": "HYG", "primary_venue": "XASE", "asset_class": "etf", "name": "iShares iBoxx High Yield Corporate Bond ETF"},
    {"primary_ticker": "GLD", "primary_venue": "XASE", "asset_class": "etf", "name": "SPDR Gold Shares"},
    {"primary_ticker": "IAU", "primary_venue": "XASE", "asset_class": "etf", "name": "iShares Gold Trust"},
    {"primary_ticker": "SLV", "primary_venue": "XASE", "asset_class": "etf", "name": "iShares Silver Trust"},
    {"primary_ticker": "USO", "primary_venue": "XASE", "asset_class": "etf", "name": "United States Oil Fund LP"},
    {"primary_ticker": "XLK", "primary_venue": "XASE", "asset_class": "etf", "name": "Technology Select Sector SPDR Fund"},
    {"primary_ticker": "XLF", "primary_venue": "XASE", "asset_class": "etf", "name": "Financial Select Sector SPDR Fund"},
    {"primary_ticker": "XLV", "primary_venue": "XASE", "asset_class": "etf", "name": "Health Care Select Sector SPDR Fund"},
    {"primary_ticker": "XLE", "primary_venue": "XASE", "asset_class": "etf", "name": "Energy Select Sector SPDR Fund"},
    {"primary_ticker": "XLY", "primary_venue": "XASE", "asset_class": "etf", "name": "Consumer Discretionary Select Sector SPDR Fund"},
    {"primary_ticker": "XLP", "primary_venue": "XASE", "asset_class": "etf", "name": "Consumer Staples Select Sector SPDR Fund"},
    {"primary_ticker": "XLI", "primary_venue": "XASE", "asset_class": "etf", "name": "Industrial Select Sector SPDR Fund"},
    {"primary_ticker": "XLU", "primary_venue": "XASE", "asset_class": "etf", "name": "Utilities Select Sector SPDR Fund"},
    {"primary_ticker": "XLRE", "primary_venue": "XASE", "asset_class": "etf", "name": "Real Estate Select Sector SPDR Fund"},
    {"primary_ticker": "XLB", "primary_venue": "XASE", "asset_class": "etf", "name": "Materials Select Sector SPDR Fund"},
    {"primary_ticker": "XLC", "primary_venue": "XASE", "asset_class": "etf", "name": "Communication Services Select Sector SPDR Fund"},
    {"primary_ticker": "XBI", "primary_venue": "XNAS", "asset_class": "etf", "name": "SPDR S&P Biotech ETF"},
    {"primary_ticker": "IBB", "primary_venue": "XNAS", "asset_class": "etf", "name": "iShares Biotechnology ETF"},
    {"primary_ticker": "ARKK", "primary_venue": "XASE", "asset_class": "etf", "name": "ARK Innovation ETF"},
    {"primary_ticker": "SMH", "primary_venue": "XASE", "asset_class": "etf", "name": "VanEck Semiconductor ETF"},
    {"primary_ticker": "SOXX", "primary_venue": "XNAS", "asset_class": "etf", "name": "iShares Semiconductor ETF"},
    {"primary_ticker": "SCHD", "primary_venue": "XASE", "asset_class": "etf", "name": "Schwab U.S. Dividend Equity ETF"},
    {"primary_ticker": "VYM", "primary_venue": "XASE", "asset_class": "etf", "name": "Vanguard High Dividend Yield ETF"},
    {"primary_ticker": "NOBL", "primary_venue": "XASE", "asset_class": "etf", "name": "ProShares S&P 500 Dividend Aristocrats ETF"},
    {"primary_ticker": "VGT", "primary_venue": "XASE", "asset_class": "etf", "name": "Vanguard Information Technology ETF"},
    {"primary_ticker": "IGV", "primary_venue": "XASE", "asset_class": "etf", "name": "iShares Expanded Tech-Software Sector ETF"},
    {"primary_ticker": "URA", "primary_venue": "XASE", "asset_class": "etf", "name": "Global X Uranium ETF"},
    {"primary_ticker": "KWEB", "primary_venue": "XNYS", "asset_class": "etf", "name": "KraneShares CSI China Internet ETF"},
    {"primary_ticker": "BITQ", "primary_venue": "XNAS", "asset_class": "etf", "name": "Bitwise Crypto Industry Innovators ETF"},
    {"primary_ticker": "BTC-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Bitcoin USD"},
    {"primary_ticker": "ETH-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Ethereum USD"},
    {"primary_ticker": "BNB-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "BNB USD"},
    {"primary_ticker": "XRP-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "XRP USD"},
    {"primary_ticker": "ADA-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Cardano USD"},
    {"primary_ticker": "SOL-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Solana USD"},
    {"primary_ticker": "DOT-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Polkadot USD"},
    {"primary_ticker": "DOGE-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Dogecoin USD"},
    {"primary_ticker": "AVAX-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Avalanche USD"},
    {"primary_ticker": "MATIC-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Polygon USD"},
    {"primary_ticker": "LINK-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Chainlink USD"},
    {"primary_ticker": "UNI-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Uniswap USD"},
    {"primary_ticker": "ATOM-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Cosmos USD"},
    {"primary_ticker": "LTC-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Litecoin USD"},
    {"primary_ticker": "NEAR-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "NEAR Protocol USD"},
    {"primary_ticker": "APT-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Aptos USD"},
    {"primary_ticker": "ARB-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Arbitrum USD"},
    {"primary_ticker": "OP-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Optimism USD"},
    {"primary_ticker": "FIL-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Filecoin USD"},
    {"primary_ticker": "ICP-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Internet Computer USD"},
    {"primary_ticker": "AAVE-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Aave USD"},
    {"primary_ticker": "MKR-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Maker USD"},
    {"primary_ticker": "GRT-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "The Graph USD"},
    {"primary_ticker": "ALGO-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Algorand USD"},
    {"primary_ticker": "XTZ-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Tezos USD"},
    {"primary_ticker": "FTM-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Fantom USD"},
    {"primary_ticker": "SAND-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "The Sandbox USD"},
    {"primary_ticker": "MANA-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Decentraland USD"},
    {"primary_ticker": "AXS-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Axie Infinity USD"},
    {"primary_ticker": "IMX-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Immutable USD"},
    {"primary_ticker": "RUNE-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "THORChain USD"},
    {"primary_ticker": "INJ-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Injective USD"},
    {"primary_ticker": "TIA-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Celestia USD"},
    {"primary_ticker": "SEI-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Sei USD"},
    {"primary_ticker": "SUI-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Sui USD"},
    {"primary_ticker": "PEPE-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Pepe USD"},
    {"primary_ticker": "WIF-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "dogwifhat USD"},
    {"primary_ticker": "BONK-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Bonk USD"},
    {"primary_ticker": "SHIB-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Shiba Inu USD"},
    {"primary_ticker": "RENDER-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Render USD"},
    {"primary_ticker": "WLD-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Worldcoin USD"},
    {"primary_ticker": "STX-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Stacks USD"},
    {"primary_ticker": "ENS-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Ethereum Name Service USD"},
    {"primary_ticker": "CRV-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Curve DAO USD"},
    {"primary_ticker": "COMP-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Compound USD"},
    {"primary_ticker": "SUSHI-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "SushiSwap USD"},
    {"primary_ticker": "1INCH-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "1inch USD"},
    {"primary_ticker": "ZEC-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Zcash USD"},
    {"primary_ticker": "DASH-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Dash USD"},
    {"primary_ticker": "BTC", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Bitcoin"},
    {"primary_ticker": "ETH", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Ethereum"},
    {"primary_ticker": "SOL", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Solana"},
    {"primary_ticker": "BNB", "primary_venue": "XCRY", "asset_class": "crypto", "name": "BNB"},
    {"primary_ticker": "XRP", "primary_venue": "XCRY", "asset_class": "crypto", "name": "XRP"},
    {"primary_ticker": "ADA", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Cardano"},
    {"primary_ticker": "DOGE", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Dogecoin"},
    {"primary_ticker": "DOT", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Polkadot"},
    {"primary_ticker": "MATIC", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Polygon"},
    {"primary_ticker": "AVAX", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Avalanche"},
    {"primary_ticker": "LINK", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Chainlink"},
    {"primary_ticker": "LTC", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Litecoin"},
    {"primary_ticker": "UNI", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Uniswap"},
    {"primary_ticker": "ATOM", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Cosmos"},
    {"primary_ticker": "USDT-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Tether USD"},
    {"primary_ticker": "USDC-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "USD Coin USD"},
    {"primary_ticker": "DAI-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Dai USD"},
    {"primary_ticker": "LDO-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Lido DAO USD"},
    {"primary_ticker": "BLUR-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Blur USD"},
    {"primary_ticker": "SNX-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Synthetix USD"},
    {"primary_ticker": "CHZ-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Chiliz USD"},
    {"primary_ticker": "ENJ-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Enjin Coin USD"},
    {"primary_ticker": "HNT-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Helium USD"},
    {"primary_ticker": "ZRX-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "0x USD"},
    {"primary_ticker": "BAND-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Band Protocol USD"},
    {"primary_ticker": "CELO-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Celo USD"},
    {"primary_ticker": "REN-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Ren USD"},
    {"primary_ticker": "OCEAN-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Ocean Protocol USD"},
    {"primary_ticker": "STORJ-USD", "primary_venue": "XCRY", "asset_class": "crypto", "name": "Storj USD"},
    {"primary_ticker": "EURUSD=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "EUR/USD"},
    {"primary_ticker": "GBPUSD=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "GBP/USD"},
    {"primary_ticker": "USDJPY=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "USD/JPY"},
    {"primary_ticker": "USDCHF=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "USD/CHF"},
    {"primary_ticker": "AUDUSD=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "AUD/USD"},
    {"primary_ticker": "USDCAD=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "USD/CAD"},
    {"primary_ticker": "NZDUSD=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "NZD/USD"},
    {"primary_ticker": "EURGBP=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "EUR/GBP"},
    {"primary_ticker": "EURJPY=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "EUR/JPY"},
    {"primary_ticker": "GBPJPY=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "GBP/JPY"},
    {"primary_ticker": "EURCHF=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "EUR/CHF"},
    {"primary_ticker": "EURAUD=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "EUR/AUD"},
    {"primary_ticker": "EURNZD=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "EUR/NZD"},
    {"primary_ticker": "EURCAD=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "EUR/CAD"},
    {"primary_ticker": "AUDJPY=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "AUD/JPY"},
    {"primary_ticker": "NZDJPY=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "NZD/JPY"},
    {"primary_ticker": "CADJPY=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "CAD/JPY"},
    {"primary_ticker": "CHFJPY=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "CHF/JPY"},
    {"primary_ticker": "AUDNZD=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "AUD/NZD"},
    {"primary_ticker": "AUDCAD=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "AUD/CAD"},
    {"primary_ticker": "USDCNH=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "USD/CNH"},
    {"primary_ticker": "USDHKD=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "USD/HKD"},
    {"primary_ticker": "USDSGD=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "USD/SGD"},
    {"primary_ticker": "USDINR=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "USD/INR"},
    {"primary_ticker": "USDMXN=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "USD/MXN"},
    {"primary_ticker": "USDBRL=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "USD/BRL"},
    {"primary_ticker": "USDZAR=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "USD/ZAR"},
    {"primary_ticker": "USDKRW=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "USD/KRW"},
    {"primary_ticker": "USDTRY=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "USD/TRY"},
    {"primary_ticker": "USDSEK=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "USD/SEK"},
    {"primary_ticker": "USDNOK=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "USD/NOK"},
    {"primary_ticker": "USDDKK=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "USD/DKK"},
    {"primary_ticker": "USDPLN=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "USD/PLN"},
    {"primary_ticker": "USDCZK=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "USD/CZK"},
    {"primary_ticker": "USDHUF=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "USD/HUF"},
    {"primary_ticker": "XAUUSD=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "Gold/USD"},
    {"primary_ticker": "XAGUSD=X", "primary_venue": "XFXS", "asset_class": "forex", "name": "Silver/USD"},
]

__all__ = ["seed_index"]
